Add card emoji tests in Apache commons sets
BNYMellon/CodeKatas pull request #115
Opened 2022-10-11 18:51 UTC by aqsa505

Signed-off-by: Aqsa Malik <aqsa.malik@bnymellon.com>

2022-10-11 20:20 UTC, donraab requested changes
Thank you for the contribution @aqsa505! A few changes requested inline.

2022-10-11 20:20 UTC, donraab commented on deck-of-cards-kata-solutions/src/test/java/bnymellon/codekatas/deckofcards/sortedset/immutable/ApacheCommonsDeckOfCardsAsSortedSetTest.java
> +                Iterate.makeString(acHand.stream().sorted().toList()));
Use Apache Commons toString method the same as the Apache List solution.

2022-10-11 20:20 UTC, donraab commented on deck-of-cards-kata-solutions/src/test/java/bnymellon/codekatas/deckofcards/sortedset/immutable/ApacheCommonsDeckOfCardsAsSortedSetTest.java
> +                        Iterate.makeString(each.stream().sorted().toList())).collect(Collectors.toSet());
Use Apache Commons toString method the same as the Apache List solution.

2022-10-11 20:20 UTC, donraab commented on deck-of-cards-kata-solutions/src/test/java/bnymellon/codekatas/deckofcards/sortedset/immutable/ApacheCommonsDeckOfCardsAsSortedSetTest.java
> +                Iterate.makeString(each.stream().sorted().toList())).collect(Collectors.toSet());
Same comment.

2022-10-11 20:20 UTC, donraab commented on deck-of-cards-kata/src/test/java/bnymellon/codekatas/deckofcards/sortedset/immutable/ApacheCommonsDeckOfCardsAsSortedSetTest.java
> +                Iterate.makeString(acHand.stream().sorted().toList()));
Same comment.

2022-10-11 20:20 UTC, donraab commented on deck-of-cards-kata/src/test/java/bnymellon/codekatas/deckofcards/sortedset/immutable/ApacheCommonsDeckOfCardsAsSortedSetTest.java
> +                Iterate.makeString(each.stream().sorted().toList())).collect(Collectors.toSet());
Same comment.

2022-10-11 20:20 UTC, donraab commented on deck-of-cards-kata/src/test/java/bnymellon/codekatas/deckofcards/sortedset/immutable/ApacheCommonsDeckOfCardsAsSortedSetTest.java
> +                Iterate.makeString(each.stream().sorted().toList())).collect(Collectors.toSet());
Same comment.

2022-10-11 20:59 UTC, aqsa505 commented
Updated other tests with Apache Commons toString.

2022-10-12 00:05 UTC, donraab approved these changes
LGTM! Thanks for the contribution @aqsa505 !

2022-10-12 00:06 UTC, merged