Add new Coffee Shop Kata and Coffee Shop Kata solution module
BNYMellon/CodeKatas pull request #139
Opened 2023-08-30 19:35 UTC by aqsa505

Signed-off-by: Aqsa Malik [aqsa.malik@bnymellon.com](mailto:aqsa.malik@bnymellon.com)

2023-08-30 21:40 UTC, tedyoung reviewed
Hope it's OK to comment on this as I wanted to try it out.

2023-08-30 21:40 UTC, tedyoung commented on coffee-shop-kata/old-java-features/src/test/java/CoffeeShopTest.java
> +        assertFalse(CoffeeDrink.class.isSealed());
isSealed() isn't available in Java 8, only 17+.

2023-08-30 21:40 UTC, tedyoung commented on coffee-shop-kata/old-java-features/src/test/java/CoffeeShopTest.java
> +        List<String> expected = List.of("HOT Americano", "HOT CARAMEL Latte with ALMOND_MILK",
List.of is Java 9+, not available in Java 8.

2023-08-30 21:40 UTC, tedyoung commented on coffee-shop-kata/old-java-features/src/test/java/CoffeeShopTest.java
> +
Missing import for assertFalse.

2023-08-30 21:40 UTC, tedyoung commented on coffee-shop-kata/old-java-features/src/test/java/CoffeeShopTest.java
> +import bnymellon.codekatas.coffeekata.food.Bagel;
Missing import for bnymellon.codekatas.coffeekata.beverage.CoffeeDrink

2023-09-04 21:33 UTC, donraab requested changes
Hi @aqsa505, looks mostly good. I have some changes request inline. Thanks!

2023-09-04 21:33 UTC, donraab commented on coffee-shop-kata/new-java-features/src/main/java/bnymellon/codekatas/coffeekata/beverage/DrinkTemperature.java
> +{HOT, ICED}
Inconsistent formatting.

2023-09-04 21:33 UTC, donraab commented on coffee-shop-kata/new-java-features/src/main/java/bnymellon/codekatas/coffeekata/beverage/FlavorSyrup.java
> +    CARAMEL}
Inconsistent formatting.

2023-09-04 21:33 UTC, donraab commented on coffee-shop-kata/old-java-features/pom.xml
> +                    <source>8</source>
While you are using old Java features, I don't think you need to keep source and target configuration at Java 8.

2023-09-04 21:33 UTC, donraab commented on coffee-shop-kata/old-java-features/src/main/java/bnymellon/codekatas/coffeekata/CoffeeShopOrder.java
> +            } else if (item instanceof Cookie)
Inconsistent formatting on else if

2023-09-04 21:33 UTC, donraab commented on coffee-shop-kata/old-java-features/src/main/java/bnymellon/codekatas/coffeekata/food/Bagel.java
> +    public boolean equals(Object obj)
You override equals but not hashCode.

2023-09-04 21:33 UTC, donraab commented on coffee-shop-kata/old-java-features/src/main/java/bnymellon/codekatas/coffeekata/food/Cookie.java
> +    public boolean equals(Object obj)
You override equals but not hashCode

2023-09-04 21:33 UTC, donraab commented on coffee-shop-kata/old-java-features/src/main/java/bnymellon/codekatas/coffeekata/food/Donut.java
> +    public boolean equals(Object obj)
You override equals but not hashCode

2023-09-04 21:33 UTC, donraab commented on coffee-shop-kata/pom.xml
> +        <maven.compiler.source>17</maven.compiler.source>
Should this be set to 20 instead of 17?

2023-09-06 18:57 UTC, donraab approved these changes
LGTM

2023-09-06 18:58 UTC, merged